<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Predicción de Aterrizaje de la Primera Etapa del Falcon 9 de Space X**[cite: 3]

 ## Laboratorio 2: Preparación de datos (Data wrangling)[cite: 3]

Tiempo estimado necesario: **60** minutos[cite: 3]

En este laboratorio, realizaremos un Análisis Exploratorio de Datos (EDA) para encontrar algunos patrones en los datos y determinar cuál sería la etiqueta (label) para entrenar modelos supervisados.[cite: 3]

En el conjunto de datos, hay varios casos diferentes en los que el propulsor no aterrizó con éxito. A veces se intentó un aterrizaje pero falló debido a un accidente; por ejemplo, <code>True Ocean</code> significa que el resultado de la misión fue un aterrizaje exitoso en una región específica del océano, mientras que <code>False Ocean</code> significa que el resultado de la misión fue un aterrizaje fallido en una región específica del océano. <code>True RTLS</code> significa que el resultado de la misión fue un aterrizaje exitoso en una plataforma terrestre <code>False RTLS</code> significa que el resultado de la misión fue un aterrizaje fallido en una plataforma terrestre. <code>True ASDS</code> significa que el resultado de la misión fue un aterrizaje exitoso en un barco dron <code>False ASDS</code> significa que el resultado de la misión fue un aterrizaje fallido en un barco dron.[cite: 3]

En este laboratorio convertiremos principalmente esos resultados en Etiquetas de Entrenamiento (Training Labels) con `1` significando que el propulsor aterrizó con éxito y `0` significando que no tuvo éxito.[cite: 3]

La primera etapa del Falcon 9 aterrizará con éxito[cite: 3]

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/api/Images/landing_1.gif)

Varios ejemplos de un aterrizaje fallido se muestran aquí:[cite: 3]

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/api/Images/crash.gif)

## Objetivos[cite: 3]
Realizar Análisis Exploratorio de Datos y determinar las Etiquetas de Entrenamiento (Training Labels)[cite: 3]

- Análisis Exploratorio de Datos[cite: 3]
- Determinar las Etiquetas de Entrenamiento[cite: 3]

----

Instale las bibliotecas a continuación[cite: 3]

In [1]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in C:\Users\Mauro\AppData\Roaming\Python\Python313\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Mauro\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Mauro\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Mauro\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Mauro\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in C:\Users\Mauro\AppData\Roaming\Python\Python313\site-packages (2.4.3)

## Importar Bibliotecas y Definir Funciones Auxiliares[cite: 3]

Importaremos las siguientes bibliotecas.[cite: 3]

In [2]:
# Pandas es una biblioteca de software escrita para el lenguaje de programación Python para manipulación y análisis de datos.[cite: 3]
import pandas as pd
# NumPy es una biblioteca para el lenguaje de programación Python, que agrega soporte para grandes arreglos y matrices multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar en estos arreglos[cite: 3]
import numpy as np

### Análisis de Datos[cite: 3]

Cargue el conjunto de datos de Space X, de la sección anterior.[cite: 3]

In [3]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")
df.head(10)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

Identifique y calcule el porcentaje de los valores faltantes en cada atributo[cite: 3]

In [4]:
df.isnull().sum()/len(df)*100

FlightNumber       0.000000
Date               0.000000
BoosterVersion     0.000000
PayloadMass        0.000000
Orbit              0.000000
LaunchSite         0.000000
Outcome            0.000000
Flights            0.000000
GridFins           0.000000
Reused             0.000000
Legs               0.000000
LandingPad        28.888889
Block              0.000000
ReusedCount        0.000000
Serial             0.000000
Longitude          0.000000
Latitude           0.000000
dtype: float64

Identifique qué columnas son numéricas y cuáles categóricas:[cite: 3]

In [5]:
df.dtypes

FlightNumber        int64
Date                  str
BoosterVersion        str
PayloadMass       float64
Orbit                 str
LaunchSite            str
Outcome               str
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad            str
Block             float64
ReusedCount         int64
Serial                str
Longitude         float64
Latitude          float64
dtype: object

### TAREA 1: Calcular el número de lanzamientos en cada sitio[cite: 3]

Los datos contienen varias instalaciones de lanzamiento de Space X: <a href='https://en.wikipedia.org/wiki/List_of_Cape_Canaveral_and_Merritt_Island_launch_sites'>Complejo de Lanzamiento Espacial 40 de Cabo Cañaveral</a> <b>VAFB SLC 4E </b>, Complejo de Lanzamiento Espacial 4E de la Base de la Fuerza Aérea Vandenberg <b>(SLC-4E)</b>, Complejo de Lanzamiento 39A del Centro Espacial Kennedy <b>KSC LC 39A </b>. La ubicación de cada lanzamiento se coloca en la columna <code>LaunchSite</code>[cite: 3]

A continuación, veamos el número de lanzamientos para cada sitio.[cite: 3]

Use el método <code>value_counts()</code> en la columna <code>LaunchSite</code> para determinar el número de lanzamientos en cada sitio:[cite: 3]

In [6]:
# Aplique value_counts() en la columna LaunchSite[cite: 3]
df['LaunchSite'].value_counts()

LaunchSite
CCAFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: count, dtype: int64

Cada lanzamiento apunta a una órbita dedicada, y aquí hay algunos tipos de órbita comunes:[cite: 3]



* <b>LEO</b>: La órbita terrestre baja (LEO) es una órbita centrada en la Tierra con una altitud de 2.000 km (1.200 millas) o menos (aproximadamente un tercio del radio de la Tierra),[1] o con al menos 11,25 períodos por día (un período orbital de 128 minutos o menos) y una excentricidad menor a 0,25.[2] La mayoría de los objetos artificiales en el espacio exterior están en LEO <a href='https://en.wikipedia.org/wiki/Low_Earth_orbit'>[1]</a>.[cite: 3]

* <b>VLEO</b>: Las Órbitas Terrestres Muy Bajas (VLEO) se pueden definir como las órbitas con una altitud media inferior a 450 km. Operar en estas órbitas puede proporcionar una serie de beneficios a las naves espaciales de observación de la Tierra, ya que la nave espacial opera más cerca de la observación<a href='https://www.researchgate.net/publication/271499606_Very_Low_Earth_Orbit_mission_concepts_for_Earth_Observation_Benefits_and_challenges'>[2]</a>.[cite: 3]


* <b>GTO</b> (Órbita de Transferencia Geoestacionaria): Una órbita de transferencia geoestacionaria es una órbita terrestre elíptica utilizada para transferir satélites de la órbita terrestre baja (LEO) a la órbita geoestacionaria (GEO). En una GTO, el perigeo (punto más cercano a la Tierra) es mucho más bajo que la altitud GEO, mientras que el apogeo (punto más lejano) alcanza aproximadamente las 22.236 millas (35.786 kilómetros) sobre el ecuador de la Tierra — la altitud de una órbita geoestacionaria. Los satélites en GTO utilizan propulsión a bordo para circularizar su órbita a altitud GEO, donde pueden proporcionar servicios como monitoreo meteorológico, comunicaciones y vigilancia. <a  href="https://www.space.com/29222-geosynchronous-orbit.html" >[3] </a>.[cite: 3]


* <b>SSO (o SO)</b>: Es una órbita sincrónica al Sol, también llamada órbita heliosincrónica, es una órbita casi polar alrededor de un planeta, en la que el satélite pasa sobre cualquier punto dado de la superficie del planeta a la misma hora solar media local <a href="https://en.wikipedia.org/wiki/Sun-synchronous_orbit">[4] <a>.[cite: 3]
    
    
    
* <b>ES-L1 </b>: En los puntos de Lagrange, las fuerzas gravitacionales de los dos grandes cuerpos se anulan de tal manera que un pequeño objeto colocado en órbita allí está en equilibrio con respecto al centro de masa de los grandes cuerpos. L1 es uno de esos puntos entre el sol y la tierra <a href="https://en.wikipedia.org/wiki/Lagrange_point#L1_point">[5]</a> .[cite: 3]
    
    
* <b>HEO</b> Una órbita altamente elíptica, es una órbita elíptica con alta excentricidad, que generalmente se refiere a una alrededor de la Tierra <a href="https://en.wikipedia.org/wiki/Highly_elliptical_orbit">[6]</a>.[cite: 3]


* <b> ISS </b> Una estación espacial modular (satélite artificial habitable) en órbita terrestre baja. Es un proyecto de colaboración multinacional entre cinco agencias espaciales participantes: NASA (Estados Unidos), Roscosmos (Rusia), JAXA (Japón), ESA (Europa) y CSA (Canadá)<a href="https://en.wikipedia.org/wiki/International_Space_Station"> [7] </a>[cite: 3]


* <b> MEO </b> Órbitas geocéntricas que varían en altitud desde 2.000 km (1.200 mi) hasta justo por debajo de la órbita geosincrónica a 35.786 kilómetros (22.236 mi). También conocida como órbita circular intermedia. Estas son "más comúnmente a 20.200 kilómetros (12.600 mi), o 20.650 kilómetros (12.830 mi), con un período orbital de 12 horas <a href="https://en.wikipedia.org/wiki/List_of_orbits"> [8] </a>[cite: 3]


* <b> HEO </b> Órbitas geocéntricas por encima de la altitud de la órbita geosincrónica (35.786 km o 22.236 mi) <a href="https://en.wikipedia.org/wiki/List_of_orbits"> [9] </a>[cite: 3]


* <b> GEO </b> Es una órbita geosincrónica circular a 35.786 kilómetros (22.236 millas) sobre el ecuador de la Tierra y que sigue la dirección de rotación de la Tierra <a href="https://en.wikipedia.org/wiki/Geostationary_orbit"> [10] </a>[cite: 3]


* <b> PO </b> Es un tipo de satélites en el que un satélite pasa por encima o casi por encima de ambos polos del cuerpo orbitado (generalmente un planeta como la Tierra <a href="https://en.wikipedia.org/wiki/Polar_orbit"> [11] </a>[cite: 3]

algunos se muestran en el siguiente gráfico:[cite: 3]

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/api/Images/Orbits.png)

### TAREA 2: Calcular el número y ocurrencia de cada órbita[cite: 3]

 Use el método <code>.value_counts()</code> para determinar el número y ocurrencia de cada órbita en la columna <code>Orbit</code>[cite: 3]


Nota: No cuente GTO, ya que es una órbita de transferencia y no geoestacionaria en sí misma.[cite: 3]

In [7]:
# Aplique value_counts en la columna Orbit[cite: 3]
df['Orbit'].value_counts()

Orbit
GTO      27
ISS      21
VLEO     14
PO        9
LEO       7
SSO       5
MEO       3
ES-L1     1
HEO       1
SO        1
GEO       1
Name: count, dtype: int64

### TAREA 3: Calcular el número y ocurrencia del resultado de la misión de las órbitas[cite: 3]

Use el método <code>.value_counts()</code> en la columna <code>Outcome</code> para determinar el número de <code>landing_outcomes</code>. Luego asígnelo a una variable landing_outcomes.[cite: 3]

In [8]:
# landing_outcomes = valores en la columna Outcome[cite: 3]
landing_outcomes = df['Outcome'].value_counts()
landing_outcomes

Outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64

<code>True Ocean</code> significa que el resultado de la misión fue un aterrizaje exitoso en una región específica del océano, mientras que <code>False Ocean</code> significa que el resultado de la misión fue un aterrizaje fallido en una región específica del océano. <code>True RTLS</code> significa que el resultado de la misión fue un aterrizaje exitoso en una plataforma terrestre <code>False RTLS</code> significa que el resultado de la misión fue un aterrizaje fallido en una plataforma terrestre. <code>True ASDS</code> significa que el resultado de la misión fue un aterrizaje exitoso en un barco dron <code>False ASDS</code> significa que el resultado de la misión fue un aterrizaje fallido en un barco dron. <code>None ASDS</code> y <code>None None</code> estos representan un fallo al aterrizar.[cite: 3]

In [9]:
for i,outcome in enumerate(landing_outcomes.keys()):
    print(i,outcome)

0 True ASDS
1 None None
2 True RTLS
3 False ASDS
4 True Ocean
5 False Ocean
6 None ASDS
7 False RTLS

Creamos un conjunto de resultados donde la segunda etapa no aterrizó con éxito:[cite: 3]

In [10]:
bad_outcomes=set(landing_outcomes.keys()[[1,3,5,6,7]])
bad_outcomes

{'False ASDS', 'False Ocean', 'False RTLS', 'None ASDS', 'None None'}

### TAREA 4: Crear una etiqueta de resultado de aterrizaje a partir de la columna Outcome[cite: 3]

Usando el <code>Outcome</code>, cree una lista donde el elemento es cero si la fila correspondiente en <code>Outcome</code> está en el conjunto <code>bad_outcome</code>; de lo contrario, es uno. Luego asígnelo a la variable <code>landing_class</code>:[cite: 3]

In [11]:
# landing_class = 0 si bad_outcome[cite: 3]
# landing_class = 1 de lo contrario[cite: 3]
landing_class = [0 if outcome in bad_outcomes else 1 for outcome in df['Outcome']]

Esta variable representará la variable de clasificación que representa el resultado de cada lanzamiento. Si el valor es cero, la primera etapa no aterrizó con éxito; uno significa que la primera etapa aterrizó con éxito[cite: 3]

In [12]:
df['Class']=landing_class
df[['Class']].head(8)

   Class
0      0
1      0
2      0
3      0
4      0
5      0
6      1
7      1

In [13]:
df.head(5)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857,0
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857,0
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857,0
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093,0
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857,0

Podemos usar la siguiente línea de código para determinar la tasa de éxito:[cite: 3]

In [14]:
df["Class"].mean()

np.float64(0.6666666666666666)

Ahora podemos exportarlo a un CSV para la siguiente sección, pero para que las respuestas sean consistentes, en el próximo laboratorio proporcionaremos datos en un rango de fechas preseleccionado.[cite: 3]

<code>df.to_csv("dataset_part_2.csv", index=False)</code>

## Autores[cite: 3]

<a href="https://www.linkedin.com/in/joseph-s-50398b136/">Joseph Santarcangelo</a> tiene un doctorado en Ingeniería Eléctrica, su investigación se centró en el uso del aprendizaje automático, el procesamiento de señales y la visión por computadora para determinar cómo los videos impactan la cognición humana. Joseph ha estado trabajando para IBM desde que completó su doctorado.[cite: 3]

<a href="https://www.linkedin.com/in/nayefaboutayoun/">Nayef Abou Tayoun</a> es un Científico de Datos en IBM y cursa un Máster en Gestión de Inteligencia Artificial en la Universidad de Queen's.[cite: 3]

<!--
## Registro de Cambios
-->

<!--
| Fecha (AAAA-MM-DD) | Versión | Cambiado Por | Descripción del Cambio      |
| ----------------- | ------- | ---------- | ----------------------- |
| 2021-08-31        | 1.1     | Lakshmi Holla    | Markdown Cambiado |
| 2020-09-20        | 1.0     | Joseph     | Múltiples Áreas Modificadas |
| 2020-11-04        | 1.1.    | Nayef      | actualizando los datos de entrada |
| 2021-05-026       | 1.1.    | Joseph      | actualizando los datos de entrada |
-->

Derechos de autor © 2021 IBM Corporation. Todos los derechos reservados.[cite: 3]